
services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp:latest
    ports:
      - "1935:1935"   
      - "8080:8080"   
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hls:/tmp/hls  
networks:
  streamnet:
    driver: bridge